user: di54xen
venv_path: /dss/dsshome1/02/di54xen/projects/oma24-proj/.venv

# Data
# ---------------------------------------------------------------------------
csv_name: dev_1000_file.csv         # CSV file with NPZ paths
test_split: 0.15                    # Fraction for held-out test set (0.0 = no test eval)

# Training hyperparameters
# ---------------------------------------------------------------------------
epochs: 80
batch_size: 12
num_workers: 14
prefetch_factor: 2

# Unique identifier for this run --> TensorBoard id
experiment_id: baseline_TorchGeoUNet_resnet50_tcd

# Model
# ---------------------------------------------------------------------------
model_name: TorchGeoUNet
# OAM_RGB_RESNET50_TCD -- ResNet50 encoder, 3ch RGB, tree-canopy pretraining
pretrained_weights: OAM_RGB_RESNET50_TCD

# Loss
# ---------------------------------------------------------------------------
use_class_weights: true
class_weights: [1.0, 50.0, 5.0]    # [background, linear_veg, patchy_veg]
