user: di54xen
epochs: 5
batch_size: 128
num_workers: 10
prefetch_factor: 8
experiment_id: UNet_exp_temp
partition: hpda2_compute_gpu
time: "03:00:00"
gpus_per_node: 1
mem_gb: 256
account: pn39sa-c
clusters: hpda2